### ISSUE TITLE
Message: boost::filesystem::create_directory: Read-only file system: "/tmp/api_usage"

### ISSUE THREAD

**Issue by abhijitpratinidhi** [ApryseSDK/pdftron-go#25]
Hi,We are using a license and wanted to convert a pdf into a PNG but we are getting a runtime exception with Message: boost::filesystem::create_directory: Read-only file system: "/tmp/api_usage" . We tried ->

1)Setting an alternative temporary path -> didnt work.
2)Granting access to /tmp/api_usage -> didnt work.

Any suggestions?

**Comment by rbarrpdftron** [comment]
Hi, is this still an issue for you?

If yes, since this issue might be related to your license key, we should move this conversation to a private channel, so if this is still an issue for you please post a ticket to link below and we will assist you further there.

https://support.apryse.com/support/tickets/new 

In the meantime I will close this issue.
